<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>IconRenderer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg" Version="3.4.8" />
    <EmbeddedResource Include="icons\**\*.svg"
                      LogicalName="IconRenderer.Icons.%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
